### PR TITLE
Add  Simplified Chinese (zh_CN) Translate

### PR DESCRIPTION
**Pull request by yi-ge**

### CODE REVIEW

**Comment by yi-ge** [comment]
I know I can't be PR in here.  But, I don't know how to do...https://tuleap-documentation.readthedocs.io/en/latest/developer-guide/patches.html#push-you-changes

**Comment by vaceletm** [comment]
Thanks for contributing this translation.

As we are not at all Chinese speaker/reader I don't know how we should review that actually. Do you know how other softwares are doing?

Plus, Tuleap grows at a rapid space, are you planning to keep up and contributing translations in the future ?

Finally, all new code now rely on gettext to manage translation, did you notice that part ?

**Comment by yi-ge** [comment]
@vaceletm Yes. I will continue to contributing translations.I'll join the team as soon as possible, in a standard way.

**Comment by vaceletm** [comment]
In current form the PR is not mergable as there are a lot of issues/warinings
From what I can check it seems that there are spaces introduced in the tab separated file.

+ I would advise to not translate site-content/tracker/* stuff as it's related to old gen trackers no longer installed.

image

**Comment by yi-ge** [comment]
@vaceletm Thank you. I will fix it.

**Comment by vaceletm** [comment]
No progress nor answers since 6m+. Closing

**Pull request closed without merging**
